CREATE TABLE IF NOT EXISTS IDN_OAUTH_CONSUMER_SECRETS (
                                                          ID INTEGER NOT NULL AUTO_INCREMENT,
                                                          SECRET_ID VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    CONSUMER_KEY VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL ,
    SECRET_VALUE VARCHAR(2048) NOT NULL,
    SECRET_HASH VARCHAR(512) NOT NULL,
    EXPIRY_TIME BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (CONSUMER_KEY) REFERENCES IDN_OAUTH_CONSUMER_APPS(CONSUMER_KEY) ON DELETE CASCADE,
    CONSTRAINT SECRET_ID_CONSTRAINT UNIQUE (SECRET_ID)
    ) ENGINE=InnoDB  CHARACTER SET = utf8 COLLATE = utf8_general_ci ;
CREATE INDEX IDX_IDN_OAUTH_CS_CK ON IDN_OAUTH_CONSUMER_SECRETS (CONSUMER_KEY);

CREATE TABLE IF NOT EXISTS AM_GW_PLATFORM_API_ARTIFACTS (
                                                            API_ID VARCHAR(255) NOT NULL,
    REVISION_ID VARCHAR(255) NOT NULL,
    GATEWAY_ENV_UUID VARCHAR(255) NOT NULL,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    ARTIFACT MEDIUMBLOB,
    TIME_STAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (DEPLOYMENT_ID),
    UNIQUE (GATEWAY_ENV_UUID, API_ID, REVISION_ID),
    FOREIGN KEY (API_ID) REFERENCES AM_GW_PUBLISHED_API_DETAILS(API_ID) ON UPDATE CASCADE
    ) ENGINE=InnoDB   CHARACTER SET = utf8 COLLATE = utf8_general_ci;
CREATE INDEX IDX_GW_PLATFORM_ARTIFACT_API_ID ON AM_GW_PLATFORM_API_ARTIFACTS (API_ID);

CREATE TABLE IF NOT EXISTS AM_GW_PLATFORM_EVENT (
                                                    ID VARCHAR(36) NOT NULL,
    GATEWAY_ID VARCHAR(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci  NOT NULL ,
    EVENT_TYPE VARCHAR(32) NOT NULL,
    PAYLOAD MEDIUMBLOB NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELIVERED_AT TIMESTAMP NULL,
    CLAIMED_AT TIMESTAMP NULL,
    CLAIMED_BY VARCHAR(36) NULL,
    PRIMARY KEY (ID),
    INDEX AM_GW_PLATFORM_EVENT_PENDING (GATEWAY_ID, DELIVERED_AT),
    FOREIGN KEY (GATEWAY_ID) REFERENCES AM_GATEWAY_ENVIRONMENT(UUID) ON DELETE CASCADE
    ) ENGINE=InnoDB  CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS AM_GATEWAY_TOKEN (
                                                ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    TOKEN_HASH VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'active',
    CREATED_AT TIMESTAMP NOT NULL,
    REVOKED_AT TIMESTAMP NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GATEWAY_ID) REFERENCES AM_GATEWAY_ENVIRONMENT(UUID) ON DELETE CASCADE
    ) ENGINE=InnoDB   CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE INDEX IDX_APGT_TOKEN_HASH ON AM_GATEWAY_TOKEN (TOKEN_HASH);


CREATE TABLE IF NOT EXISTS AM_API_KEY (
                                          API_KEY_UUID VARCHAR(64) PRIMARY KEY,
    NAME VARCHAR(512) NOT NULL,
    API_KEY_HASH VARCHAR(512) NOT NULL UNIQUE,
    KEY_TYPE VARCHAR(100),
    API_KEY_PROPERTIES BLOB DEFAULT NULL,
    AUTHZ_USER VARCHAR(512),
    TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALIDITY_PERIOD BIGINT,
    LAST_USED TIMESTAMP NULL DEFAULT NULL,
    STATUS VARCHAR(100) DEFAULT 'ACTIVE' NOT NULL
    ) ENGINE=InnoDB   CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS AM_API_KEY_API_MAPPING (
                                                      API_KEY_UUID VARCHAR(256),
    API_UUID VARCHAR(256),
    PRIMARY KEY (API_KEY_UUID, API_UUID),
    FOREIGN KEY (API_KEY_UUID) REFERENCES AM_API_KEY(API_KEY_UUID),
    FOREIGN KEY (API_UUID) REFERENCES AM_API(API_UUID)
    ) ENGINE=InnoDB  CHARACTER SET = utf8 COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS AM_API_KEY_APPLICATION_MAPPING (
                                                              API_KEY_UUID VARCHAR(256),
    APPLICATION_UUID VARCHAR(256) CHARACTER SET latin1 COLLATE latin1_swedish_ci,
    PRIMARY KEY (API_KEY_UUID, APPLICATION_UUID),
    FOREIGN KEY (API_KEY_UUID) REFERENCES AM_API_KEY(API_KEY_UUID),
    FOREIGN KEY (APPLICATION_UUID) REFERENCES AM_APPLICATION(UUID)
    ) ENGINE=InnoDB  CHARACTER SET = utf8 COLLATE = utf8_general_ci;


SELECT TABLE_NAME FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN (
                     'IDN_OAUTH_CONSUMER_SECRETS',
                     'AM_GW_PLATFORM_API_ARTIFACTS',
                     'AM_GW_PLATFORM_EVENT',
                     'AM_GATEWAY_TOKEN',
                     'AM_API_KEY',
                     'AM_API_KEY_API_MAPPING',
                     'AM_API_KEY_APPLICATION_MAPPING'
    );